### ISSUE TITLE
Здесь и далее...

### ISSUE THREAD

**Issue by sicom-dn** [Denkalinovsky/WP-Form#3]
https://github.com/Denkalinovsky/WP-Form/blob/651d29b2defa2238a2e717cca05e9bff195ab32a/index.php#L31

А что это за закомментированный код? Зачем он?

**Comment by Denkalinovsky** [comment]
я удалил не нужный код в "index.php"
изначально не знал, как правильно подключить все скрипты, поэтому оставил

**Comment by sicom-dn** [comment]
ок
