### ISSUE TITLE
Почему тут "vanilla js"?

### ISSUE THREAD

**Issue by sicom-dn** [Denkalinovsky/WP-Form#4]
https://github.com/Denkalinovsky/WP-Form/blob/651d29b2defa2238a2e717cca05e9bff195ab32a/assets/js/app.js#L39

Странно вот что: часть кода написана на jQuery, а часть на "ванильном" JS. Тут надо бы что-то одно. Думаю стоит переписать на jQuery. Тот же самый функционал

**Comment by Denkalinovsky** [comment]
Переписал этот код на jQuery
Теперь это выглядит так:

```
$(document).ready(() => {
		let thisForm = $('form');;
		$(thisForm).find('[name = "captcha-value"]')[0].textContent = `${a} + ${b} = ?`;
	});
```

так же была функция 

![image](https://user-images.githubusercontent.com/37328420/108357219-31703080-71fe-11eb-9474-daaf59510636.png)

которую тоже переписал, теперь выглядит вот так: 

![image](https://user-images.githubusercontent.com/37328420/108357285-464cc400-71fe-11eb-9396-0e4e7666529e.png)

**Comment by sicom-dn** [comment]
ok
